services:
  dev:
    build:
      dockerfile: src/main/docker/Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/opt/tesseract/src
    environment:
      TESSERACT_DATA_LANGS: "fra,eng,deu"